export const OFFSHORE_INTERCEPTION_STATES = {
  PATROL: 'PATROL',
  SUSPICIOUS_TARGET_DETECTED: 'SUSPICIOUS_TARGET_DETECTED',
  RADIO_CHALLENGE: 'RADIO_CHALLENGE',
  RETURN_TO_PATROL_NON_THREAT: 'RETURN_TO_PATROL_NON_THREAT',
  INTERCEPT_40_KNOTS: 'INTERCEPT_40_KNOTS',
  APPROACH_TO_5000: 'APPROACH_TO_5000',
  ZIGZAG_APPROACH: 'ZIGZAG_APPROACH',
  APPROACH_TO_2000: 'APPROACH_TO_2000',
  WARNING_FLARES: 'WARNING_FLARES',
  APPROACH_TO_1000: 'APPROACH_TO_1000',
  WAITING_FOR_OPERATOR_APPROVAL: 'WAITING_FOR_OPERATOR_APPROVAL',
  VIOLENT_INTERCEPTION_APPROVED: 'VIOLENT_INTERCEPTION_APPROVED',
  MAG_FIRE_BLOCKED_UNSAFE_RIG_LINE: 'MAG_FIRE_BLOCKED_UNSAFE_RIG_LINE',
  MAG_DESTRUCTIVE_FIRE: 'MAG_DESTRUCTIVE_FIRE',
  TARGET_NEUTRALIZED: 'TARGET_NEUTRALIZED',
  RETURN_TO_3000_YARD_PATROL: 'RETURN_TO_3000_YARD_PATROL',
  MAG_FAILED: 'MAG_FAILED',
  CLOSE_RANGE_RAM_PREP: 'CLOSE_RANGE_RAM_PREP',
  MAX_SPEED_PURSUIT: 'MAX_SPEED_PURSUIT',
  RAM_ATTEMPT: 'RAM_ATTEMPT',
  COLLISION_RESOLUTION: 'COLLISION_RESOLUTION',
  MISSION_FAILED: 'MISSION_FAILED',
};

export const offshoreInterceptionConfig = {
  detectionRangeYards: 12000,
  radioChallengeStartYards: 12000,
  radioChallengeEndYards: 5000,
  dynamicPatrolRadiusYards: 3000,
  staticGuardRadiusYards: 500,
  safetyRangeFromTargetYards: 500,
  initialInterceptSpeedKnots: 40,
  zigzagTriggerDistanceYards: 5000,
  zigzagSpeedKnots: 20,
  zigzagAngleMinDeg: 30,
  zigzagAngleMaxDeg: 60,
  warningFlareTriggerDistanceYards: 2000,
  warningFlareOffsetAnglesDeg: [-30, 30],
  warningFlarePhaseSpeedKnots: 30,
  operatorApprovalTriggerDistanceYards: 1000,
  magDestructiveSuccessProbability: 0.7,
  ramTriggerDistanceYards: 200,
  maxSpeedKnots: 50,
  cruiseSpeedKnots: 22,
  magRangeYards: 2000,
  magFiringEnvelopeHalfAngleDeg: 30,
  unsafeRigLineHalfAngleDeg: 30,
  radioAnswerProbability: 0.3,
  zigzagSwitchIntervalSec: 8,
  warningFlareIntervalSec: 4,
};

export function createInitialInterceptionStatus(overrides = {}) {
  return {
    state: OFFSHORE_INTERCEPTION_STATES.PATROL,
    assignedDefenderId: null,
    lastStateChangeSec: 0,
    radioDecisionMade: false,
    targetAnsweredRadio: false,
    interceptStarted: false,
    signalingActive: false,
    zigzagDirection: -1,
    zigzagAngleDeg: offshoreInterceptionConfig.zigzagAngleMinDeg,
    lastWarningFlareSec: null,
    nextWarningFlareSideDeg: offshoreInterceptionConfig.warningFlareOffsetAnglesDeg[0],
    operatorApprovalRequested: false,
    operatorApprovalResolved: false,
    operatorApprovalGranted: false,
    magAttempted: false,
    magSucceeded: false,
    magFailed: false,
    ramIntentActive: false,
    targetNeutralized: false,
    returnedToPatrol: false,
    missionFailed: false,
    ...overrides,
  };
}
